name: Actividad Ingesta de Datos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: paso1 - crea entorno virtual
        run: python -m venv venv
      - name: paso2 - activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: paso3 - actualizar pip
        run: pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: pip install -e .

      - name: paso5 - Ejecutar ingesta
        run: python src/ibgd/ingesta.py
      - name: Guardar archivos generados
        uses: actions/upload-artifact@v4
        with:
          name: archivos-generados
          path: src/ibgd/static/
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: generación informe prueba json
          file_pattern: "src/ibgd/static/**/*"
          commit_user_name: Natalia Rojas [GitHub Actions]
          commit_user_email: natalia.rojas@est.iudigital.edu.co
          commit_author: Natalia Rojas <natalia.rojas@est.iudigital.edu.co>
      - name: Listar archivos generados
        run: ls -R src/ibgd/static
      


